export const actionEnums = {
    PLAYERS_REQUEST_COMPLETED: "PLAYERS_REQUEST_COMPLETED",
    STARTERS_ADD_PLAYER_TO_LINEUP: "STARTERS_ADD_PLAYER_TO_LINEUP",
    STARTERS_REMOVE_PLAYER_FROM_LINEUP: "STARTERS_REMOVE_PLAYER_FROM_LINEUP",
    STARTERS_LOAD_PLAYERS: "STARTERS_LOAD_PLAYERS",
    PLAYERS_ADD_TO_BENCH: "PLAYERS_ADD_TO_BENCH",
    PLAYERS_REMOVE_FROM_BENCH: "PLAYERS_REMOVE_FROM_BENCH"
}