import {PlayerEntity} from "../model/player";


export const playersMockData: PlayerEntity[] = [
    {id: 80, name: 'Aybar', position: '1', average: 0},
    {id: 32, name: 'Barnes', position: '1', average: 0},
    {id: 70, name: 'Brasier', position: '1', average: 0},
    {id: 48, name: 'Brewer', position: '1', average: 0},
    {id: 31, name: 'Brice', position: '1', average: 0},
    {id: 46, name: 'Covey', position: '1', average: 0},
    {id: 17, name: 'Eovaldi', position: '1', average: 0},
    {id: 68, name: 'Godley', position: '1', average: 0},
    {id: 56, name: 'Hall', position: '1', average: 0},
    {id: 81, name: 'Hart', position: '1', average: 0},
    {id: 63, name: 'Hernandez', position: '1', average: 0},
    {id: 74, name: 'Kickham', position: '1', average: 0},
    {id: 77, name: 'Leyer', position: '1', average: 0},
    {id: 22, name: 'Mazza', position: '1', average: 0},
    {id: 54, name: 'Perez', position: '1', average: 0},
    {id: 77, name: 'Pivetta', position: '1', average: 0},
    {id: 57, name: 'Rodriguez', position: '1', average: 0},
    {id: 41, name: 'Sale', position: '1', average: 0},
    {id: 59, name: 'Srpings', position: '1', average: 0},
    {id: 79, name: 'Stock', position: '1', average: 0},
    {id: 66, name: 'Tapia', position: '1', average: 0},
    {id: 72, name: 'Taylor', position: '1', average: 0},
    {id: 61, name: 'Triggs', position: '1', average: 0},
    {id: 71, name: 'Valdez', position: '1', average: 0},
    {id: 64, name: 'Walden', position: '1', average: 0},
    {id: 65, name: 'Weber', position: '1', average: 0},
    {id: 73, name: 'Grullon', position: '2', average: 0},
    {id: 25, name: 'Plawecki', position: '2', average: 0},
    {id: 7, name: 'Vazquez', position: '2', average: 0},
    {id: 36, name: 'Arauz', position: 'INF', average: 0},
    {id: 39, name: 'Arroyo', position: 'OF', average: 310},
    {id: 2, name: 'Bogaerts', position: '6', average: 275},
    {id: 43, name: 'Chatham', position: '6', average: 282},
    {id: 23, name: 'Chavis', position: '4', average: 211},
    {id: 29, name: 'Dalbec', position: '3', average: 272},
    {id: 11, name: 'Devers', position: '5', average: 400},
    {id: 30, name: 'Lin', position: 'INF', average: 255},
    {id: 60, name: 'Munoz', position: '7', average: 250},
    {id: 15, name: 'Pedroia', position: '4', average: 429},
    {id: 3, name: 'Peraza', position: '4', average: 0},
    {id: 16, name: 'Benintendi', position: '7', average: 400},
    {id: 19, name: 'Bradley Jr.', position: '8', average: 255},
    {id: 28, name: 'Martinez', position: 'DH', average: 250},
    {id: 99, name: 'Verdugo', position: '9', average: 429},
    {id: 39, name: 'Wilson', position: 'OF', average: 0}
];